name: CI & Deploy (cPanel FTPS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --experimental-vm-modules
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm test

  build-and-deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      # optional: see what's being uploaded
      - name: List dist contents
        run: |
          echo "---- dist ----"
          ls -la dist
          echo "--------------"

      # dry run first (no upload) to verify connection & paths
      - name: FTP Deploy (dry run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}        # e.g. ftp.danielchambe.rs (hostname only)
          username: ${{ secrets.FTP_USERNAME }}    # e.g. portfolio@danielchambe.rs
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: dist/
          server-dir: /public_html/                # from your `lftp` pwd
          dry-run: true
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**

      # real upload
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: dist/
          server-dir: /public_html/
          log-level: verbose
          timeout: 60000
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**